//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basedata21
{
    using System;
    using System.Collections.Generic;
    
    public partial class МОЛ
    {
        public int Табельный_номер { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Телефон { get; set; }
    }
}
