//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basedata21
{
    using System;
    using System.Collections.Generic;
    
    public partial class Основные_средства
    {
        public int Инвентарный_номер { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Код_группы { get; set; }
        public Nullable<int> Первоначальная_стоимость { get; set; }
        public Nullable<System.DateTime> Дата_ввода_в_эксплуатацию { get; set; }
        public Nullable<int> Код_подразделения { get; set; }
    }
}
